"""Pull the called-out sentences out of a set of pass records into one file.

    python3 passes/collate_callouts.py VOICE   -> passes/VOICE_CALLOUTS.md
    python3 passes/collate_callouts.py VOICE2  -> passes/VOICE2_CALLOUTS.md

Seventeen agents name their sections seventeen ways ("Call-outs", "Called out,
not changed", "Write-up required"), so heading text is not a reliable handle.
The handle is the format itself: a call-out is required to carry a **Current:**
line, so any section that has one gets collected and any section that does not
is skipped. That also picks up the entries agents filed under headings like
"left alone as deliberate", which are call-outs whatever they are called.
"""
import glob, re, sys

PREFIX = sys.argv[1] if len(sys.argv) > 1 else "VOICE"

HEAD = f"""# {PREFIX}: every sentence called out and not changed

One file for all of it. Each span's agent changed what it was sure of and wrote
up what it was not, and this is that second list. Nothing here has been changed
in the manuscript. Every entry gives the sentence as it stands, why the voice is
wrong, why it was not changed, and replacements to choose from.

Generated by `passes/collate_callouts.py {PREFIX}`.

"""

out, n, files = [HEAD], 0, 0
for f in sorted(glob.glob(f"passes/{PREFIX}_*.md")):
    span = re.search(rf"{PREFIX}_(\d+)_(\d+)\.md$", f)
    if not span:
        continue
    text = open(f).read()
    # Split into level-2 sections, keeping each heading with its body.
    parts = re.split(r"\n(?=## )", text)
    kept = [p.strip() for p in parts if "**Current:**" in p]
    if not kept:
        continue
    files += 1
    body = "\n\n".join(kept)
    # The per-file headings become level 3 under the span heading.
    body = re.sub(r"^## ", "### ", body, flags=re.M)
    body = re.sub(r"^#### ", "##### ", body, flags=re.M)
    out.append(f"\n## Chapters {int(span[1])} and {int(span[2])}\n\n{body}\n")
    n += body.count("**Current:**")

out.append(f"\n---\n\n{n} sentences called out across {files} spans.\n")
open(f"passes/{PREFIX}_CALLOUTS.md", "w").write("\n".join(out))
print(n, "call-outs from", files, "spans ->", f"passes/{PREFIX}_CALLOUTS.md")
