"""Pull the called-out sections out of every passes/VOICE_*.md into one file.

The per-span records are the agents' own; this only gathers them, so rerunning
it after a late span reports is safe and picks that span up.
"""
import glob, re, textwrap

HEAD = """# Voice pass: everything called out and not changed

One file for all of it. Each span's agent fixed what it was sure of and wrote
up what it was not, and this is the second list. Nothing here has been changed
in the manuscript. Every entry gives the sentence as it stands, why the voice
looks wrong, why the agent would not change it on its own, and replacements to
choose from.

Generated by `scratchpad/collate.py` from the `passes/VOICE_*.md` records.

"""

out = [HEAD]
n = 0
for f in sorted(glob.glob("passes/VOICE_*.md")):
    if f.endswith("VOICE_CALLOUTS.md"):
        continue
    t = open(f).read()
    m = re.search(r"\n## .*(?:Called out|CALLED OUT|Not changed).*\n", t)
    if not m:
        continue
    rest = t[m.end():]
    nxt = re.search(r"\n## ", rest)
    body = rest[:nxt.start()] if nxt else rest
    body = body.strip()
    span = re.search(r"VOICE_(\d+)_(\d+)", f)
    out.append(f"\n## Chapters {int(span[1])} and {int(span[2])}\n\n{body}\n")
    n += len(re.findall(r"^### ", body, re.M))

out.append(f"\n---\n\n{n} sentences called out across the whole book.\n")
open("passes/VOICE_CALLOUTS.md", "w").write("\n".join(out))
print(n, "call-outs collated")
