#!/usr/bin/env python3
"""Re-point the prose-violation reports at the lines their quotes now sit on.

The chapter files under chapters/ are regenerated by split_manuscript.py, and
anything that changes their shape moves every line below it. Adding the
month-and-year under each title pushes the whole body down by two. Renumbering
a chapter, or a later re-split, can move things too.

The reports cite a line number and a verbatim quote. The quote is the durable
half: it survives a reflow, and the line number does not. So this finds each
quote in the chapter it belongs to and rewrites the line number to match.

    python3 resync_violations.py --check     report what would move, write nothing
    python3 resync_violations.py             rewrite the line numbers

Where a quote appears more than once in its chapter, the occurrence nearest the
line already recorded wins, which keeps a repeated line pinned to the instance
the agent meant. A quote that has vanished from the chapter is reported and left
untouched, because that means the prose changed rather than moved, and only a
person can decide what the finding now refers to.
"""

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPORTS = HERE / "prose_violations"


def norm(t):
    return re.sub(r"\s+", " ", t.replace("“", '"').replace("”", '"')
                  .replace("‘", "'").replace("’", "'")).strip()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", type=Path, default=HERE)
    ap.add_argument("--reports", type=Path, default=REPORTS)
    ap.add_argument("--check", action="store_true", help="report, write nothing")
    a = ap.parse_args()

    if not a.reports.is_dir():
        sys.exit(f"error: no report directory at {a.reports}")

    cache, moved, same, lost = {}, 0, 0, []
    for f in sorted(a.reports.glob("*.jsonl")):
        entries, changed = [], False
        for raw in f.read_text(encoding="utf-8").split("\n"):
            if not raw.strip():
                continue
            e = json.loads(raw)
            target = a.root / e["file"]
            if target not in cache:
                cache[target] = [norm(l) for l in
                                 target.read_text(encoding="utf-8").split("\n")]
            lines = cache[target]
            quote = norm(e["quote"])
            hits = [i + 1 for i, l in enumerate(lines) if quote and quote in l]
            if not hits:
                lost.append((f.name, e["line"], e["quote"][:60]))
                entries.append(e)
                continue
            best = min(hits, key=lambda h: abs(h - e["line"]))
            if best != e["line"]:
                moved += 1
                changed = True
                e["line"] = best
            else:
                same += 1
            entries.append(e)
        if changed and not a.check:
            f.write_text("".join(json.dumps(e, ensure_ascii=False) + "\n"
                                 for e in entries), encoding="utf-8")

    if lost:
        print("QUOTE NO LONGER IN THE CHAPTER")
        for name, line, snippet in lost:
            print(f"  {name} (was line {line}): {snippet}")

    verb = "would move" if a.check else "moved"
    print(f"\n{moved} {verb}, {same} already correct, {len(lost)} not found.")
    return 1 if lost else 0


if __name__ == "__main__":
    sys.exit(main())
